---
- name: Set up packages keys
  command: 'pacman-key --init'

- name: Populate keys
  command: 'pacman-key --populate archlinux'

- name: Update package database
  pacman:
    update_cache: true

- name: Install packages
  pacman:
    name:
      - vim
      - zsh
      - neofetch
      - python
      - curl
      - httpie
      - sudo
      - htop
      - the_silver_searcher
      - tree
      - git
      - docker
      - xclip
      - ipython
      - xorg
      - lightdm
      - lightdm-gtk-greeter
      - xfce4
      - terminator

- name: Add group
  group:
    name: '{{ group }}'

- name: Add user
  user:
    name: '{{ user }}'
    group: '{{ group }}'
    groups: wheel
    password: '{{ password }}'
    shell: /bin/zsh

- name: Place sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers
    mode: '0600'
    validate: /usr/sbin/visudo -cf %s

- name: Place aliases
  copy:
    src: .aliases
    dest: '/home/{{ user }}/.aliases'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0600'

- name: Add lightdm to autorun
  service:
    name: lightdm
    state: started
    enabled: true
