---
- name: Set up packages keys
  command: 'pacman-key --init'

- name: Populate keys
  command: 'pacman-key --populate archlinux'

- name: Update package database
  pacman:
    update_cache: true

- name: Install packages
  pacman:
    name: '{{ packages }}'

- name: Add group
  group:
    name: '{{ group }}'

- name: Create home folders
  file:
    dest: '/etc/skel/{{ item }}'
    state: directory
  with_items: '{{ home_dirs }}'

- name: Add user
  user:
    name: '{{ user }}'
    group: '{{ group }}'
    groups: wheel,docker
    password: '{{ password }}'
    shell: /bin/zsh

- name: Place sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers
    mode: '0600'
    validate: /usr/sbin/visudo -cf %s

- name: Place aliases
  copy:
    src: .aliases
    dest: '/home/{{ user }}/.aliases'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0600'

- name: Add lightdm to autorun
  service:
    name: lightdm
    state: started
    enabled: true

- name: Add docker to autorun
  service:
    name: docker
    state: started
    enabled: true

- name: Create config dir for i3status
  file:
    dest: '/home/{{ user }}/.config/i3status'
    state: directory

- name: Place i3status config
  copy:
    src: i3status.conf
    dest: '/home/{{ user }}/.config/i3status/config'
